name: Build

on:
  workflow_dispatch:
  push:
    branches:
    - 'master'
    tags:
    - 'source/v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set-up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with Gradle
      run: gradle build

    - name: Copy metadata to dist
      run: cp action.yml build/js/

    - name: Prepare tag
      id: tag
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        VERSION="${GITHUB_REF##refs/tags/source/}"
        echo "version=${VERSION}" >>$GITHUB_OUTPUT

    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        user_name: "Il Harper"
        user_email: "hi@ilharper.com"
        publish_branch: nightly
        publish_dir: ./build/js
        enable_jekyll: true # Not to create .nojekyll since this is not a gh page
        commit_message: "chore: publish ${{ steps.tag.outputs.version }}"
        tag_name: ${{ steps.tag.outputs.version }} # Wouldn't create if empty
        tag_message: Publish ${{ steps.tag.outputs.version }}

    - name: Tag Tracking
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: H4M5TER/tag-semver-tracking@v1
      with:
        tag: ${{ steps.tag.outputs.version }}
        token: ${{ secrets.GITHUB_TOKEN }}
