name: Build

on:
  workflow_dispatch:
  push:
    branches:
    - 'master'
    tags:
    - 'source/v*.*.*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Validate wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Set-up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with Gradle
      run: gradle build

    - name: Copy metadata to dist
      if: github.event_name != 'pull_request'
      run: cp action.yml build/js/

    - name: Prepare tag
      id: tag
      if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/')
      run: |
        VERSION="${GITHUB_REF##refs/tags/source/}"
        echo "::set-output name=version::${VERSION}"

    - name: Publish
      if: github.event_name != 'pull_request'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        user_name: "Il Harper"
        user_email: "hi@ilharper.com"
        publish_branch: nightly
        publish_dir: ./build/js
        enable_jekyll: true # Not to create .nojekyll since this is not a gh page
        commit_message: "chore: publish ${{ steps.tag.outputs.version }}"
        tag_name: ${{ steps.tag.outputs.version }} # Wouldn't create if empty
        tag_message: Publish ${{ steps.tag.outputs.version }}

    - name: Tag Tracking
      if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/')
      uses: H4M5TER/tag-semver-tracking@v1
      with:
        tag: ${{ steps.tag.outputs.version }}
        token: ${{ secrets.GITHUB_TOKEN }}
